<?php
	require_once("IDAO.class.php");
	require_once("DBFactory.class.php");
	include_once("Area_conhecimento.class.php");
	
	class Area_conhecimentoDAO implements IDAO{
	    
		private static $lastId;
		
		public function insertData($obj){
			$agronomia = $obj->getAgronomia();
			$arquitetura_urbanismo = $obj->getArquitetura_urbanismo();
			$biologia_geral = $obj->getBiologia_geral();
			$direito = $obj->getDireito();
			$educacao = $obj->getEducacao();
			$filosofia = $obj->getFilosofia();
			$geociencias = $obj->getGeociencias();
			$historia = $obj->getHistoria();
			$matematica = $obj->getMatematica();
			$quimica = $obj->getQuimica();
			$saude_coletiva = $obj->getSaude_coletiva();
			$turismo = $obj->getTurismo();
			$antropologia = $obj->getAntropologia();
			$arte = $obj->getArte();
			$comunicacao_jornalismo = $obj->getComunicacao_jornalismo();
			$ecologia = $obj->getEcologia();
			$engenharia_sanitaria = $obj->getEngenharia_sanitaria();
			$fisica = $obj->getFisica();
			$geografia = $obj->getGeografia();
			$letras = $obj->getLetras();
			$psicologia = $obj->getPsicologia();
			$rec_florestais_eng_florestal = $obj->getRec_florestais_eng_florestal();
			$sociologia = $obj->getSociologia();
			$administracao = $obj->getAdministracao();
			$administracao_rural = $obj->getAdministracao_rural();
			$astronomia = $obj->getAstronomia();
			$biomedicina = $obj->getBiomedicina();
			$botanica = $obj->getBotanica();
			$carreira_religiosa = $obj->getCarreira_religiosa();
			$ciencia_informacao = $obj->getCiencia_informacao();
			$ciencia_politica = $obj->getCiencia_politica();
			$ciencias_atuariais = $obj->getCiencias_atuariais();
			$comunicacao = $obj->getComunicacao();
			$demografia = $obj->getDemografia();
			$desenho_projetos = $obj->getDesenho_projetos();
			$diplomacia = $obj->getDiplomacia();
			$economia_domestica = $obj->getEconomia_domestica();
			$enfermagem = $obj->getEnfermagem();
			$engenharia_agricola = $obj->getEngenharia_agricola();
			$engenharia_cartografica = $obj->getEngenharia_cartografica();
			$engenharia_agrimensura = $obj->getEngenharia_agrimensura();
			$engenharia_materiais_metalurgica = $obj->getEngenharia_materiais_metalurgica();
			$engenharia_producao = $obj->getEngenharia_producao();
			$engenharia_eletrica = $obj->getEngenharia_eletrica();
			$engenharia_naval_oceanica = $obj->getEngenharia_naval_oceanica();
			$engenharia_quimica = $obj->getEngenharia_quimica();
			$estudos_sociais = $obj->getEstudos_sociais();
			$farmacologia = $obj->getFarmacologia();
			$fisioterapia_terapia_ocupacional = $obj->getFisioterapia_terapia_ocupacional();
			$genetica = $obj->getGenetica();
			$imunologia = $obj->getImunologia();
			$medicina = $obj->getMedicina();
			$microbiologia = $obj->getMicrobiologia();
			$museologia = $obj->getMuseologia();
			$oceanografia = $obj->getOceanografia();
			$parasitologia = $obj->getParasitologia();
			$probabilidade_estatistica = $obj->getProbabilidade_estatistica();
			$recursos_pesqueiros_engenharia_pesca = $obj->getRecursos_pesqueiros_engenharia_pesca();
			$relacoes_publicas = $obj->getRelacoes_publicas();
			$servico_social = $obj->getServico_social();
			$zoologia = $obj->getZoologia();
			$administracao_hospitalar = $obj->getAdministracao_hospitalar();
			$arqueologia = $obj->getArqueologia();
			$biofisica = $obj->getBiofisica();
			$bioquimica = $obj->getBioquimica();
			$carreira_militar = $obj->getCarreira_militar();
			$ciencia_computacao = $obj->getCiencia_computacao();
			$ciencia_tecnologia_alimentos = $obj->getCiencia_tecnologia_alimentos();
			$ciencias = $obj->getCiencias();
			$ciencias_sociais = $obj->getCiencias_sociais();
			$decoracao = $obj->getDecoracao();
			$desenho_moda = $obj->getDesenho_moda();
			$desenho_industrial = $obj->getDesenho_industrial();
			$economia = $obj->getEconomia();
			$educacao_fisica = $obj->getEducacao_fisica();
			$engenharia_aeroespacial = $obj->getEngenharia_aeroespacial();
			$engenharia_biomedica = $obj->getEngenharia_biomedica();
			$engenharia_civil = $obj->getEngenharia_civil();
			$engenharia_armamentos = $obj->getEngenharia_armamentos();
			$engenharia_minas = $obj->getEngenharia_minas();
			$engenharia_transportes = $obj->getEngenharia_transportes();
			$engenharia_mecatronica = $obj->getEngenharia_mecatronica();
			$engenharia_nuclear = $obj->getEngenharia_nuclear();
			$engenharia_textil = $obj->getEngenharia_textil();
			$farmacia = $obj->getFarmacia();
			$fisiologia = $obj->getFisiologia();
			$fonoaudiologia = $obj->getFonoaudiologia();
			$historia_natural = $obj->getHistoria_natural();
			$linguistica = $obj->getLinguistica();
			$medicina_veterinaria = $obj->getMedicina_veterinaria();
			$morfologia = $obj->getMorfologia();
			$nutricao = $obj->getNutricao();
			$odontologia = $obj->getOdontologia();
			$planejamento_urbano_regional = $obj->getPlanejamento_urbano_regional();
			$quimica_industrial = $obj->getQuimica_industrial();
			$relacoes_internacionais = $obj->getRelacoes_internacionais();
			$secretariado_executiva = $obj->getSecretariado_executiva();
			$teologia = $obj->getTeologia();
			$zootecnia = $obj->getZootecnia();
			$qagronomia = $obj->getQagronomia();
			$qarquitetura_urbanismo = $obj->getQarquitetura_urbanismo();
			$qbiologia_geral = $obj->getQbiologia_geral();
			$qdireito = $obj->getQdireito();
			$qeducacao = $obj->getQeducacao();
			$qfilosofia = $obj->getQfilosofia();
			$qgeociencias = $obj->getQgeociencias();
			$qhistoria = $obj->getQhistoria();
			$qmatematica = $obj->getQmatematica();
			$qquimica = $obj->getQquimica();
			$qsaude_coletiva = $obj->getQsaude_coletiva();
			$qturismo = $obj->getQturismo();
			$qantropologia = $obj->getQantropologia();
			$qarte = $obj->getQarte();
			$qcomunicacao_jornalismo = $obj->getQcomunicacao_jornalismo();
			$qecologia = $obj->getQecologia();
			$qengenharia_sanitaria = $obj->getQengenharia_sanitaria();
			$qfisica = $obj->getQfisica();
			$qgeografia = $obj->getQgeografia();
			$qletras = $obj->getQletras();
			$qpsicologia = $obj->getQpsicologia();
			$qrec_florestais_eng_florestal = $obj->getQrec_florestais_eng_florestal();
			$qsociologia = $obj->getQsociologia();
			$qadministracao = $obj->getQadministracao();
			$qadministracao_rural = $obj->getQadministracao_rural();
			$qastronomia = $obj->getQastronomia();
			$qbiomedicina = $obj->getQbiomedicina();
			$qbotanica = $obj->getQbotanica();
			$qcarreira_religiosa = $obj->getQcarreira_religiosa();
			$qciencia_informacao = $obj->getQciencia_informacao();
			$qciencia_politica = $obj->getQciencia_politica();
			$qciencias_atuariais = $obj->getQciencias_atuariais();
			$qcomunicacao = $obj->getQcomunicacao();
			$qdemografia = $obj->getQdemografia();
			$qdesenho_projetos = $obj->getQdesenho_projetos();
			$qdiplomacia = $obj->getQdiplomacia();
			$qeconomia_domestica = $obj->getQeconomia_domestica();
			$qenfermagem = $obj->getQenfermagem();
			$qengenharia_agricola = $obj->getQengenharia_agricola();
			$qengenharia_cartografica = $obj->getQengenharia_cartografica();
			$qengenharia_agrimensura = $obj->getQengenharia_agrimensura();
			$qengenharia_materiais_metalurgica = $obj->getQengenharia_materiais_metalurgica();
			$qengenharia_producao = $obj->getQengenharia_producao();
			$qengenharia_eletrica = $obj->getQengenharia_eletrica();
			$qengenharia_naval_oceanica = $obj->getQengenharia_naval_oceanica();
			$qengenharia_quimica = $obj->getQengenharia_quimica();
			$qestudos_sociais = $obj->getQestudos_sociais();
			$qfarmacologia = $obj->getQfarmacologia();
			$qfisioterapia_terapia_ocupacional = $obj->getQfisioterapia_terapia_ocupacional();
			$qgenetica = $obj->getQgenetica();
			$qimunologia = $obj->getQimunologia();
			$qmedicina = $obj->getQmedicina();
			$qmicrobiologia = $obj->getQmicrobiologia();
			$qmuseologia = $obj->getQmuseologia();
			$qoceanografia = $obj->getQoceanografia();
			$qparasitologia = $obj->getQparasitologia();
			$qprobabilidade_estatistica = $obj->getQprobabilidade_estatistica();
			$qrecursos_pesqueiros_engenharia_pesca = $obj->getQrecursos_pesqueiros_engenharia_pesca();
			$qrelacoes_publicas = $obj->getQrelacoes_publicas();
			$qservico_social = $obj->getQservico_social();
			$qzoologia = $obj->getQzoologia();
			$qadministracao_hospitalar = $obj->getQadministracao_hospitalar();
			$qarqueologia = $obj->getQarqueologia();
			$qbiofisica = $obj->getQbiofisica();
			$qbioquimica = $obj->getQbioquimica();
			$qcarreira_militar = $obj->getQcarreira_militar();
			$qciencia_computacao = $obj->getQciencia_computacao();
			$qciencia_tecnologia_alimentos = $obj->getQciencia_tecnologia_alimentos();
			$qciencias = $obj->getQciencias();
			$qciencias_sociais = $obj->getQciencias_sociais();
			$qdecoracao = $obj->getQdecoracao();
			$qdesenho_moda = $obj->getQdesenho_moda();
			$qdesenho_industrial = $obj->getQdesenho_industrial();
			$qeconomia = $obj->getQeconomia();
			$qeducacao_fisica = $obj->getQeducacao_fisica();
			$qengenharia_aeroespacial = $obj->getQengenharia_aeroespacial();
			$qengenharia_biomedica = $obj->getQengenharia_biomedica();
			$qengenharia_civil = $obj->getQengenharia_civil();
			$qengenharia_armamentos = $obj->getQengenharia_armamentos();
			$qengenharia_minas = $obj->getQengenharia_minas();
			$qengenharia_transportes = $obj->getQengenharia_transportes();
			$qengenharia_mecatronica = $obj->getQengenharia_mecatronica();
			$qengenharia_nuclear = $obj->getQengenharia_nuclear();
			$qengenharia_textil = $obj->getQengenharia_textil();
			$qfarmacia = $obj->getQfarmacia();
			$qfisiologia = $obj->getQfisiologia();
			$qfonoaudiologia = $obj->getQfonoaudiologia();
			$qhistoria_natural = $obj->getQhistoria_natural();
			$qlinguistica = $obj->getQlinguistica();
			$qmedicina_veterinaria = $obj->getQmedicina_veterinaria();
			$qmorfologia = $obj->getQmorfologia();
			$qnutricao = $obj->getQnutricao();
			$qodontologia = $obj->getQodontologia();
			$qplanejamento_urbano_regional = $obj->getQplanejamento_urbano_regional();
			$qquimica_industrial = $obj->getQquimica_industrial();
			$qrelacoes_internacionais = $obj->getQrelacoes_internacionais();
			$qsecretariado_executiva = $obj->getQsecretariado_executiva();
			$qteologia = $obj->getQteologia();
			$qzootecnia = $obj->getQzootecnia();
			$qarea_conhecimento = $obj->getQarea_conhecimento();

			$agronomia = addslashes($agronomia);
			$arquitetura_urbanismo = addslashes($arquitetura_urbanismo);
			$biologia_geral = addslashes($biologia_geral);
			$direito = addslashes($direito);
			$educacao = addslashes($educacao);
			$filosofia = addslashes($filosofia);
			$geociencias = addslashes($geociencias);
			$historia = addslashes($historia);
			$matematica = addslashes($matematica);
			$quimica = addslashes($quimica);
			$saude_coletiva = addslashes($saude_coletiva);
			$turismo = addslashes($turismo);
			$antropologia = addslashes($antropologia);
			$arte = addslashes($arte);
			$comunicacao_jornalismo = addslashes($comunicacao_jornalismo);
			$ecologia = addslashes($ecologia);
			$engenharia_sanitaria = addslashes($engenharia_sanitaria);
			$fisica = addslashes($fisica);
			$geografia = addslashes($geografia);
			$letras = addslashes($letras);
			$psicologia = addslashes($psicologia);
			$rec_florestais_eng_florestal = addslashes($rec_florestais_eng_florestal);
			$sociologia = addslashes($sociologia);
			$administracao = addslashes($administracao);
			$administracao_rural = addslashes($administracao_rural);
			$astronomia = addslashes($astronomia);
			$biomedicina = addslashes($biomedicina);
			$botanica = addslashes($botanica);
			$carreira_religiosa = addslashes($carreira_religiosa);
			$ciencia_informacao = addslashes($ciencia_informacao);
			$ciencia_politica = addslashes($ciencia_politica);
			$ciencias_atuariais = addslashes($ciencias_atuariais);
			$comunicacao = addslashes($comunicacao);
			$demografia = addslashes($demografia);
			$desenho_projetos = addslashes($desenho_projetos);
			$diplomacia = addslashes($diplomacia);
			$economia_domestica = addslashes($economia_domestica);
			$enfermagem = addslashes($enfermagem);
			$engenharia_agricola = addslashes($engenharia_agricola);
			$engenharia_cartografica = addslashes($engenharia_cartografica);
			$engenharia_agrimensura = addslashes($engenharia_agrimensura);
			$engenharia_materiais_metalurgica = addslashes($engenharia_materiais_metalurgica);
			$engenharia_producao = addslashes($engenharia_producao);
			$engenharia_eletrica = addslashes($engenharia_eletrica);
			$engenharia_naval_oceanica = addslashes($engenharia_naval_oceanica);
			$engenharia_quimica = addslashes($engenharia_quimica);
			$estudos_sociais = addslashes($estudos_sociais);
			$farmacologia = addslashes($farmacologia);
			$fisioterapia_terapia_ocupacional = addslashes($fisioterapia_terapia_ocupacional);
			$genetica = addslashes($genetica);
			$imunologia = addslashes($imunologia);
			$medicina = addslashes($medicina);
			$microbiologia = addslashes($microbiologia);
			$museologia = addslashes($museologia);
			$oceanografia = addslashes($oceanografia);
			$parasitologia = addslashes($parasitologia);
			$probabilidade_estatistica = addslashes($probabilidade_estatistica);
			$recursos_pesqueiros_engenharia_pesca = addslashes($recursos_pesqueiros_engenharia_pesca);
			$relacoes_publicas = addslashes($relacoes_publicas);
			$servico_social = addslashes($servico_social);
			$zoologia = addslashes($zoologia);
			$administracao_hospitalar = addslashes($administracao_hospitalar);
			$arqueologia = addslashes($arqueologia);
			$biofisica = addslashes($biofisica);
			$bioquimica = addslashes($bioquimica);
			$carreira_militar = addslashes($carreira_militar);
			$ciencia_computacao = addslashes($ciencia_computacao);
			$ciencia_tecnologia_alimentos = addslashes($ciencia_tecnologia_alimentos);
			$ciencias = addslashes($ciencias);
			$ciencias_sociais = addslashes($ciencias_sociais);
			$decoracao = addslashes($decoracao);
			$desenho_moda = addslashes($desenho_moda);
			$desenho_industrial = addslashes($desenho_industrial);
			$economia = addslashes($economia);
			$educacao_fisica = addslashes($educacao_fisica);
			$engenharia_aeroespacial = addslashes($engenharia_aeroespacial);
			$engenharia_biomedica = addslashes($engenharia_biomedica);
			$engenharia_civil = addslashes($engenharia_civil);
			$engenharia_armamentos = addslashes($engenharia_armamentos);
			$engenharia_minas = addslashes($engenharia_minas);
			$engenharia_transportes = addslashes($engenharia_transportes);
			$engenharia_mecatronica = addslashes($engenharia_mecatronica);
			$engenharia_nuclear = addslashes($engenharia_nuclear);
			$engenharia_textil = addslashes($engenharia_textil);
			$farmacia = addslashes($farmacia);
			$fisiologia = addslashes($fisiologia);
			$fonoaudiologia = addslashes($fonoaudiologia);
			$historia_natural = addslashes($historia_natural);
			$linguistica = addslashes($linguistica);
			$medicina_veterinaria = addslashes($medicina_veterinaria);
			$morfologia = addslashes($morfologia);
			$nutricao = addslashes($nutricao);
			$odontologia = addslashes($odontologia);
			$planejamento_urbano_regional = addslashes($planejamento_urbano_regional);
			$quimica_industrial = addslashes($quimica_industrial);
			$relacoes_internacionais = addslashes($relacoes_internacionais);
			$secretariado_executiva = addslashes($secretariado_executiva);
			$teologia = addslashes($teologia);
			$zootecnia = addslashes($zootecnia);
			$qagronomia = addslashes($qagronomia);
			$qarquitetura_urbanismo = addslashes($qarquitetura_urbanismo);
			$qbiologia_geral = addslashes($qbiologia_geral);
			$qdireito = addslashes($qdireito);
			$qeducacao = addslashes($qeducacao);
			$qfilosofia = addslashes($qfilosofia);
			$qgeociencias = addslashes($qgeociencias);
			$qhistoria = addslashes($qhistoria);
			$qmatematica = addslashes($qmatematica);
			$qquimica = addslashes($qquimica);
			$qsaude_coletiva = addslashes($qsaude_coletiva);
			$qturismo = addslashes($qturismo);
			$qantropologia = addslashes($qantropologia);
			$qarte = addslashes($qarte);
			$qcomunicacao_jornalismo = addslashes($qcomunicacao_jornalismo);
			$qecologia = addslashes($qecologia);
			$qengenharia_sanitaria = addslashes($qengenharia_sanitaria);
			$qfisica = addslashes($qfisica);
			$qgeografia = addslashes($qgeografia);
			$qletras = addslashes($qletras);
			$qpsicologia = addslashes($qpsicologia);
			$qrec_florestais_eng_florestal = addslashes($qrec_florestais_eng_florestal);
			$qsociologia = addslashes($qsociologia);
			$qadministracao = addslashes($qadministracao);
			$qadministracao_rural = addslashes($qadministracao_rural);
			$qastronomia = addslashes($qastronomia);
			$qbiomedicina = addslashes($qbiomedicina);
			$qbotanica = addslashes($qbotanica);
			$qcarreira_religiosa = addslashes($qcarreira_religiosa);
			$qciencia_informacao = addslashes($qciencia_informacao);
			$qciencia_politica = addslashes($qciencia_politica);
			$qciencias_atuariais = addslashes($qciencias_atuariais);
			$qcomunicacao = addslashes($qcomunicacao);
			$qdemografia = addslashes($qdemografia);
			$qdesenho_projetos = addslashes($qdesenho_projetos);
			$qdiplomacia = addslashes($qdiplomacia);
			$qeconomia_domestica = addslashes($qeconomia_domestica);
			$qenfermagem = addslashes($qenfermagem);
			$qengenharia_agricola = addslashes($qengenharia_agricola);
			$qengenharia_cartografica = addslashes($qengenharia_cartografica);
			$qengenharia_agrimensura = addslashes($qengenharia_agrimensura);
			$qengenharia_materiais_metalurgica = addslashes($qengenharia_materiais_metalurgica);
			$qengenharia_producao = addslashes($qengenharia_producao);
			$qengenharia_eletrica = addslashes($qengenharia_eletrica);
			$qengenharia_naval_oceanica = addslashes($qengenharia_naval_oceanica);
			$qengenharia_quimica = addslashes($qengenharia_quimica);
			$qestudos_sociais = addslashes($qestudos_sociais);
			$qfarmacologia = addslashes($qfarmacologia);
			$qfisioterapia_terapia_ocupacional = addslashes($qfisioterapia_terapia_ocupacional);
			$qgenetica = addslashes($qgenetica);
			$qimunologia = addslashes($qimunologia);
			$qmedicina = addslashes($qmedicina);
			$qmicrobiologia = addslashes($qmicrobiologia);
			$qmuseologia = addslashes($qmuseologia);
			$qoceanografia = addslashes($qoceanografia);
			$qparasitologia = addslashes($qparasitologia);
			$qprobabilidade_estatistica = addslashes($qprobabilidade_estatistica);
			$qrecursos_pesqueiros_engenharia_pesca = addslashes($qrecursos_pesqueiros_engenharia_pesca);
			$qrelacoes_publicas = addslashes($qrelacoes_publicas);
			$qservico_social = addslashes($qservico_social);
			$qzoologia = addslashes($qzoologia);
			$qadministracao_hospitalar = addslashes($qadministracao_hospitalar);
			$qarqueologia = addslashes($qarqueologia);
			$qbiofisica = addslashes($qbiofisica);
			$qbioquimica = addslashes($qbioquimica);
			$qcarreira_militar = addslashes($qcarreira_militar);
			$qciencia_computacao = addslashes($qciencia_computacao);
			$qciencia_tecnologia_alimentos = addslashes($qciencia_tecnologia_alimentos);
			$qciencias = addslashes($qciencias);
			$qciencias_sociais = addslashes($qciencias_sociais);
			$qdecoracao = addslashes($qdecoracao);
			$qdesenho_moda = addslashes($qdesenho_moda);
			$qdesenho_industrial = addslashes($qdesenho_industrial);
			$qeconomia = addslashes($qeconomia);
			$qeducacao_fisica = addslashes($qeducacao_fisica);
			$qengenharia_aeroespacial = addslashes($qengenharia_aeroespacial);
			$qengenharia_biomedica = addslashes($qengenharia_biomedica);
			$qengenharia_civil = addslashes($qengenharia_civil);
			$qengenharia_armamentos = addslashes($qengenharia_armamentos);
			$qengenharia_minas = addslashes($qengenharia_minas);
			$qengenharia_transportes = addslashes($qengenharia_transportes);
			$qengenharia_mecatronica = addslashes($qengenharia_mecatronica);
			$qengenharia_nuclear = addslashes($qengenharia_nuclear);
			$qengenharia_textil = addslashes($qengenharia_textil);
			$qfarmacia = addslashes($qfarmacia);
			$qfisiologia = addslashes($qfisiologia);
			$qfonoaudiologia = addslashes($qfonoaudiologia);
			$qhistoria_natural = addslashes($qhistoria_natural);
			$qlinguistica = addslashes($qlinguistica);
			$qmedicina_veterinaria = addslashes($qmedicina_veterinaria);
			$qmorfologia = addslashes($qmorfologia);
			$qnutricao = addslashes($qnutricao);
			$qodontologia = addslashes($qodontologia);
			$qplanejamento_urbano_regional = addslashes($qplanejamento_urbano_regional);
			$qquimica_industrial = addslashes($qquimica_industrial);
			$qrelacoes_internacionais = addslashes($qrelacoes_internacionais);
			$qsecretariado_executiva = addslashes($qsecretariado_executiva);
			$qteologia = addslashes($qteologia);
			$qzootecnia = addslashes($qzootecnia);
			$qarea_conhecimento = addslashes($qarea_conhecimento);
			
			$sql = "INSERT INTO area_conhecimento VALUES('NULL','$agronomia','$arquitetura_urbanismo','$biologia_geral','$direito','$educacao','$filosofia','$geociencias','$historia','$matematica','$quimica','$saude_coletiva','$turismo','$antropologia','$arte','$comunicacao_jornalismo','$ecologia','$engenharia_sanitaria','$fisica','$geografia','$letras','$psicologia','$rec_florestais_eng_florestal','$sociologia','$administracao','$administracao_rural','$astronomia','$biomedicina','$botanica','$carreira_religiosa','$ciencia_informacao','$ciencia_politica','$ciencias_atuariais','$comunicacao','$demografia','$desenho_projetos','$diplomacia','$economia_domestica','$enfermagem','$engenharia_agricola','$engenharia_cartografica','$engenharia_agrimensura','$engenharia_materiais_metalurgica','$engenharia_producao','$engenharia_eletrica','$engenharia_naval_oceanica','$engenharia_quimica','$estudos_sociais','$farmacologia','$fisioterapia_terapia_ocupacional','$genetica','$imunologia','$medicina','$microbiologia','$museologia','$oceanografia','$parasitologia','$probabilidade_estatistica','$recursos_pesqueiros_engenharia_pesca','$relacoes_publicas','$servico_social','$zoologia','$administracao_hospitalar','$arqueologia','$biofisica','$bioquimica','$carreira_militar','$ciencia_computacao','$ciencia_tecnologia_alimentos','$ciencias','$ciencias_sociais','$decoracao','$desenho_moda','$desenho_industrial','$economia','$educacao_fisica','$engenharia_aeroespacial','$engenharia_biomedica','$engenharia_civil','$engenharia_armamentos','$engenharia_minas','$engenharia_transportes','$engenharia_mecatronica','$engenharia_nuclear','$engenharia_textil','$farmacia','$fisiologia','$fonoaudiologia','$historia_natural','$linguistica','$medicina_veterinaria','$morfologia','$nutricao','$odontologia','$planejamento_urbano_regional','$quimica_industrial','$relacoes_internacionais','$secretariado_executiva','$teologia','$zootecnia','$qagronomia','$qarquitetura_urbanismo','$qbiologia_geral','$qdireito','$qeducacao','$qfilosofia','$qgeociencias','$qhistoria','$qmatematica','$qquimica','$qsaude_coletiva','$qturismo','$qantropologia','$qarte','$qcomunicacao_jornalismo','$qecologia','$qengenharia_sanitaria','$qfisica','$qgeografia','$qletras','$qpsicologia','$qrec_florestais_eng_florestal','$qsociologia','$qadministracao','$qadministracao_rural','$qastronomia','$qbiomedicina','$qbotanica','$qcarreira_religiosa','$qciencia_informacao','$qciencia_politica','$qciencias_atuariais','$qcomunicacao','$qdemografia','$qdesenho_projetos','$qdiplomacia','$qeconomia_domestica','$qenfermagem','$qengenharia_agricola','$qengenharia_cartografica','$qengenharia_agrimensura','$qengenharia_materiais_metalurgica','$qengenharia_producao','$qengenharia_eletrica','$qengenharia_naval_oceanica','$qengenharia_quimica','$qestudos_sociais','$qfarmacologia','$qfisioterapia_terapia_ocupacional','$qgenetica','$qimunologia','$qmedicina','$qmicrobiologia','$qmuseologia','$qoceanografia','$qparasitologia','$qprobabilidade_estatistica','$qrecursos_pesqueiros_engenharia_pesca','$qrelacoes_publicas','$qservico_social','$qzoologia','$qadministracao_hospitalar','$qarqueologia','$qbiofisica','$qbioquimica','$qcarreira_militar','$qciencia_computacao','$qciencia_tecnologia_alimentos','$qciencias','$qciencias_sociais','$qdecoracao','$qdesenho_moda','$qdesenho_industrial','$qeconomia','$qeducacao_fisica','$qengenharia_aeroespacial','$qengenharia_biomedica','$qengenharia_civil','$qengenharia_armamentos','$qengenharia_minas','$qengenharia_transportes','$qengenharia_mecatronica','$qengenharia_nuclear','$qengenharia_textil','$qfarmacia','$qfisiologia','$qfonoaudiologia','$qhistoria_natural','$qlinguistica','$qmedicina_veterinaria','$qmorfologia','$qnutricao','$qodontologia','$qplanejamento_urbano_regional','$qquimica_industrial','$qrelacoes_internacionais','$qsecretariado_executiva','$qteologia','$qzootecnia','$qarea_conhecimento')";

			DBFactory::getConnection();
			$result = DBFactory::query($sql);
			
			echo DBFactory::msg(DBFactory::getConnection());
			self::setLastId();
			
			DBFactory::closeConnection();
			return $result;
		}
		
		public function updateData($obj){
			DBFactory::getConnection();
			
			$id = $obj->getId();
			$id = (int) $id;
			$id = mysql_real_escape_string($id);
			$agronomia = $obj->getAgronomia();
			$arquitetura_urbanismo = $obj->getArquitetura_urbanismo();
			$biologia_geral = $obj->getBiologia_geral();
			$direito = $obj->getDireito();
			$educacao = $obj->getEducacao();
			$filosofia = $obj->getFilosofia();
			$geociencias = $obj->getGeociencias();
			$historia = $obj->getHistoria();
			$matematica = $obj->getMatematica();
			$quimica = $obj->getQuimica();
			$saude_coletiva = $obj->getSaude_coletiva();
			$turismo = $obj->getTurismo();
			$antropologia = $obj->getAntropologia();
			$arte = $obj->getArte();
			$comunicacao_jornalismo = $obj->getComunicacao_jornalismo();
			$ecologia = $obj->getEcologia();
			$engenharia_sanitaria = $obj->getEngenharia_sanitaria();
			$fisica = $obj->getFisica();
			$geografia = $obj->getGeografia();
			$letras = $obj->getLetras();
			$psicologia = $obj->getPsicologia();
			$rec_florestais_eng_florestal = $obj->getRec_florestais_eng_florestal();
			$sociologia = $obj->getSociologia();
			$administracao = $obj->getAdministracao();
			$administracao_rural = $obj->getAdministracao_rural();
			$astronomia = $obj->getAstronomia();
			$biomedicina = $obj->getBiomedicina();
			$botanica = $obj->getBotanica();
			$carreira_religiosa = $obj->getCarreira_religiosa();
			$ciencia_informacao = $obj->getCiencia_informacao();
			$ciencia_politica = $obj->getCiencia_politica();
			$ciencias_atuariais = $obj->getCiencias_atuariais();
			$comunicacao = $obj->getComunicacao();
			$demografia = $obj->getDemografia();
			$desenho_projetos = $obj->getDesenho_projetos();
			$diplomacia = $obj->getDiplomacia();
			$economia_domestica = $obj->getEconomia_domestica();
			$enfermagem = $obj->getEnfermagem();
			$engenharia_agricola = $obj->getEngenharia_agricola();
			$engenharia_cartografica = $obj->getEngenharia_cartografica();
			$engenharia_agrimensura = $obj->getEngenharia_agrimensura();
			$engenharia_materiais_metalurgica = $obj->getEngenharia_materiais_metalurgica();
			$engenharia_producao = $obj->getEngenharia_producao();
			$engenharia_eletrica = $obj->getEngenharia_eletrica();
			$engenharia_naval_oceanica = $obj->getEngenharia_naval_oceanica();
			$engenharia_quimica = $obj->getEngenharia_quimica();
			$estudos_sociais = $obj->getEstudos_sociais();
			$farmacologia = $obj->getFarmacologia();
			$fisioterapia_terapia_ocupacional = $obj->getFisioterapia_terapia_ocupacional();
			$genetica = $obj->getGenetica();
			$imunologia = $obj->getImunologia();
			$medicina = $obj->getMedicina();
			$microbiologia = $obj->getMicrobiologia();
			$museologia = $obj->getMuseologia();
			$oceanografia = $obj->getOceanografia();
			$parasitologia = $obj->getParasitologia();
			$probabilidade_estatistica = $obj->getProbabilidade_estatistica();
			$recursos_pesqueiros_engenharia_pesca = $obj->getRecursos_pesqueiros_engenharia_pesca();
			$relacoes_publicas = $obj->getRelacoes_publicas();
			$servico_social = $obj->getServico_social();
			$zoologia = $obj->getZoologia();
			$administracao_hospitalar = $obj->getAdministracao_hospitalar();
			$arqueologia = $obj->getArqueologia();
			$biofisica = $obj->getBiofisica();
			$bioquimica = $obj->getBioquimica();
			$carreira_militar = $obj->getCarreira_militar();
			$ciencia_computacao = $obj->getCiencia_computacao();
			$ciencia_tecnologia_alimentos = $obj->getCiencia_tecnologia_alimentos();
			$ciencias = $obj->getCiencias();
			$ciencias_sociais = $obj->getCiencias_sociais();
			$decoracao = $obj->getDecoracao();
			$desenho_moda = $obj->getDesenho_moda();
			$desenho_industrial = $obj->getDesenho_industrial();
			$economia = $obj->getEconomia();
			$educacao_fisica = $obj->getEducacao_fisica();
			$engenharia_aeroespacial = $obj->getEngenharia_aeroespacial();
			$engenharia_biomedica = $obj->getEngenharia_biomedica();
			$engenharia_civil = $obj->getEngenharia_civil();
			$engenharia_armamentos = $obj->getEngenharia_armamentos();
			$engenharia_minas = $obj->getEngenharia_minas();
			$engenharia_transportes = $obj->getEngenharia_transportes();
			$engenharia_mecatronica = $obj->getEngenharia_mecatronica();
			$engenharia_nuclear = $obj->getEngenharia_nuclear();
			$engenharia_textil = $obj->getEngenharia_textil();
			$farmacia = $obj->getFarmacia();
			$fisiologia = $obj->getFisiologia();
			$fonoaudiologia = $obj->getFonoaudiologia();
			$historia_natural = $obj->getHistoria_natural();
			$linguistica = $obj->getLinguistica();
			$medicina_veterinaria = $obj->getMedicina_veterinaria();
			$morfologia = $obj->getMorfologia();
			$nutricao = $obj->getNutricao();
			$odontologia = $obj->getOdontologia();
			$planejamento_urbano_regional = $obj->getPlanejamento_urbano_regional();
			$quimica_industrial = $obj->getQuimica_industrial();
			$relacoes_internacionais = $obj->getRelacoes_internacionais();
			$secretariado_executiva = $obj->getSecretariado_executiva();
			$teologia = $obj->getTeologia();
			$zootecnia = $obj->getZootecnia();
			$qagronomia = $obj->getQagronomia();
			$qarquitetura_urbanismo = $obj->getQarquitetura_urbanismo();
			$qbiologia_geral = $obj->getQbiologia_geral();
			$qdireito = $obj->getQdireito();
			$qeducacao = $obj->getQeducacao();
			$qfilosofia = $obj->getQfilosofia();
			$qgeociencias = $obj->getQgeociencias();
			$qhistoria = $obj->getQhistoria();
			$qmatematica = $obj->getQmatematica();
			$qquimica = $obj->getQquimica();
			$qsaude_coletiva = $obj->getQsaude_coletiva();
			$qturismo = $obj->getQturismo();
			$qantropologia = $obj->getQantropologia();
			$qarte = $obj->getQarte();
			$qcomunicacao_jornalismo = $obj->getQcomunicacao_jornalismo();
			$qecologia = $obj->getQecologia();
			$qengenharia_sanitaria = $obj->getQengenharia_sanitaria();
			$qfisica = $obj->getQfisica();
			$qgeografia = $obj->getQgeografia();
			$qletras = $obj->getQletras();
			$qpsicologia = $obj->getQpsicologia();
			$qrec_florestais_eng_florestal = $obj->getQrec_florestais_eng_florestal();
			$qsociologia = $obj->getQsociologia();
			$qadministracao = $obj->getQadministracao();
			$qadministracao_rural = $obj->getQadministracao_rural();
			$qastronomia = $obj->getQastronomia();
			$qbiomedicina = $obj->getQbiomedicina();
			$qbotanica = $obj->getQbotanica();
			$qcarreira_religiosa = $obj->getQcarreira_religiosa();
			$qciencia_informacao = $obj->getQciencia_informacao();
			$qciencia_politica = $obj->getQciencia_politica();
			$qciencias_atuariais = $obj->getQciencias_atuariais();
			$qcomunicacao = $obj->getQcomunicacao();
			$qdemografia = $obj->getQdemografia();
			$qdesenho_projetos = $obj->getQdesenho_projetos();
			$qdiplomacia = $obj->getQdiplomacia();
			$qeconomia_domestica = $obj->getQeconomia_domestica();
			$qenfermagem = $obj->getQenfermagem();
			$qengenharia_agricola = $obj->getQengenharia_agricola();
			$qengenharia_cartografica = $obj->getQengenharia_cartografica();
			$qengenharia_agrimensura = $obj->getQengenharia_agrimensura();
			$qengenharia_materiais_metalurgica = $obj->getQengenharia_materiais_metalurgica();
			$qengenharia_producao = $obj->getQengenharia_producao();
			$qengenharia_eletrica = $obj->getQengenharia_eletrica();
			$qengenharia_naval_oceanica = $obj->getQengenharia_naval_oceanica();
			$qengenharia_quimica = $obj->getQengenharia_quimica();
			$qestudos_sociais = $obj->getQestudos_sociais();
			$qfarmacologia = $obj->getQfarmacologia();
			$qfisioterapia_terapia_ocupacional = $obj->getQfisioterapia_terapia_ocupacional();
			$qgenetica = $obj->getQgenetica();
			$qimunologia = $obj->getQimunologia();
			$qmedicina = $obj->getQmedicina();
			$qmicrobiologia = $obj->getQmicrobiologia();
			$qmuseologia = $obj->getQmuseologia();
			$qoceanografia = $obj->getQoceanografia();
			$qparasitologia = $obj->getQparasitologia();
			$qprobabilidade_estatistica = $obj->getQprobabilidade_estatistica();
			$qrecursos_pesqueiros_engenharia_pesca = $obj->getQrecursos_pesqueiros_engenharia_pesca();
			$qrelacoes_publicas = $obj->getQrelacoes_publicas();
			$qservico_social = $obj->getQservico_social();
			$qzoologia = $obj->getQzoologia();
			$qadministracao_hospitalar = $obj->getQadministracao_hospitalar();
			$qarqueologia = $obj->getQarqueologia();
			$qbiofisica = $obj->getQbiofisica();
			$qbioquimica = $obj->getQbioquimica();
			$qcarreira_militar = $obj->getQcarreira_militar();
			$qciencia_computacao = $obj->getQciencia_computacao();
			$qciencia_tecnologia_alimentos = $obj->getQciencia_tecnologia_alimentos();
			$qciencias = $obj->getQciencias();
			$qciencias_sociais = $obj->getQciencias_sociais();
			$qdecoracao = $obj->getQdecoracao();
			$qdesenho_moda = $obj->getQdesenho_moda();
			$qdesenho_industrial = $obj->getQdesenho_industrial();
			$qeconomia = $obj->getQeconomia();
			$qeducacao_fisica = $obj->getQeducacao_fisica();
			$qengenharia_aeroespacial = $obj->getQengenharia_aeroespacial();
			$qengenharia_biomedica = $obj->getQengenharia_biomedica();
			$qengenharia_civil = $obj->getQengenharia_civil();
			$qengenharia_armamentos = $obj->getQengenharia_armamentos();
			$qengenharia_minas = $obj->getQengenharia_minas();
			$qengenharia_transportes = $obj->getQengenharia_transportes();
			$qengenharia_mecatronica = $obj->getQengenharia_mecatronica();
			$qengenharia_nuclear = $obj->getQengenharia_nuclear();
			$qengenharia_textil = $obj->getQengenharia_textil();
			$qfarmacia = $obj->getQfarmacia();
			$qfisiologia = $obj->getQfisiologia();
			$qfonoaudiologia = $obj->getQfonoaudiologia();
			$qhistoria_natural = $obj->getQhistoria_natural();
			$qlinguistica = $obj->getQlinguistica();
			$qmedicina_veterinaria = $obj->getQmedicina_veterinaria();
			$qmorfologia = $obj->getQmorfologia();
			$qnutricao = $obj->getQnutricao();
			$qodontologia = $obj->getQodontologia();
			$qplanejamento_urbano_regional = $obj->getQplanejamento_urbano_regional();
			$qquimica_industrial = $obj->getQquimica_industrial();
			$qrelacoes_internacionais = $obj->getQrelacoes_internacionais();
			$qsecretariado_executiva = $obj->getQsecretariado_executiva();
			$qteologia = $obj->getQteologia();
			$qzootecnia = $obj->getQzootecnia();
			$qarea_conhecimento = $obj->getQarea_conhecimento();

			$agronomia = addslashes($agronomia);
			$arquitetura_urbanismo = addslashes($arquitetura_urbanismo);
			$biologia_geral = addslashes($biologia_geral);
			$direito = addslashes($direito);
			$educacao = addslashes($educacao);
			$filosofia = addslashes($filosofia);
			$geociencias = addslashes($geociencias);
			$historia = addslashes($historia);
			$matematica = addslashes($matematica);
			$quimica = addslashes($quimica);
			$saude_coletiva = addslashes($saude_coletiva);
			$turismo = addslashes($turismo);
			$antropologia = addslashes($antropologia);
			$arte = addslashes($arte);
			$comunicacao_jornalismo = addslashes($comunicacao_jornalismo);
			$ecologia = addslashes($ecologia);
			$engenharia_sanitaria = addslashes($engenharia_sanitaria);
			$fisica = addslashes($fisica);
			$geografia = addslashes($geografia);
			$letras = addslashes($letras);
			$psicologia = addslashes($psicologia);
			$rec_florestais_eng_florestal = addslashes($rec_florestais_eng_florestal);
			$sociologia = addslashes($sociologia);
			$administracao = addslashes($administracao);
			$administracao_rural = addslashes($administracao_rural);
			$astronomia = addslashes($astronomia);
			$biomedicina = addslashes($biomedicina);
			$botanica = addslashes($botanica);
			$carreira_religiosa = addslashes($carreira_religiosa);
			$ciencia_informacao = addslashes($ciencia_informacao);
			$ciencia_politica = addslashes($ciencia_politica);
			$ciencias_atuariais = addslashes($ciencias_atuariais);
			$comunicacao = addslashes($comunicacao);
			$demografia = addslashes($demografia);
			$desenho_projetos = addslashes($desenho_projetos);
			$diplomacia = addslashes($diplomacia);
			$economia_domestica = addslashes($economia_domestica);
			$enfermagem = addslashes($enfermagem);
			$engenharia_agricola = addslashes($engenharia_agricola);
			$engenharia_cartografica = addslashes($engenharia_cartografica);
			$engenharia_agrimensura = addslashes($engenharia_agrimensura);
			$engenharia_materiais_metalurgica = addslashes($engenharia_materiais_metalurgica);
			$engenharia_producao = addslashes($engenharia_producao);
			$engenharia_eletrica = addslashes($engenharia_eletrica);
			$engenharia_naval_oceanica = addslashes($engenharia_naval_oceanica);
			$engenharia_quimica = addslashes($engenharia_quimica);
			$estudos_sociais = addslashes($estudos_sociais);
			$farmacologia = addslashes($farmacologia);
			$fisioterapia_terapia_ocupacional = addslashes($fisioterapia_terapia_ocupacional);
			$genetica = addslashes($genetica);
			$imunologia = addslashes($imunologia);
			$medicina = addslashes($medicina);
			$microbiologia = addslashes($microbiologia);
			$museologia = addslashes($museologia);
			$oceanografia = addslashes($oceanografia);
			$parasitologia = addslashes($parasitologia);
			$probabilidade_estatistica = addslashes($probabilidade_estatistica);
			$recursos_pesqueiros_engenharia_pesca = addslashes($recursos_pesqueiros_engenharia_pesca);
			$relacoes_publicas = addslashes($relacoes_publicas);
			$servico_social = addslashes($servico_social);
			$zoologia = addslashes($zoologia);
			$administracao_hospitalar = addslashes($administracao_hospitalar);
			$arqueologia = addslashes($arqueologia);
			$biofisica = addslashes($biofisica);
			$bioquimica = addslashes($bioquimica);
			$carreira_militar = addslashes($carreira_militar);
			$ciencia_computacao = addslashes($ciencia_computacao);
			$ciencia_tecnologia_alimentos = addslashes($ciencia_tecnologia_alimentos);
			$ciencias = addslashes($ciencias);
			$ciencias_sociais = addslashes($ciencias_sociais);
			$decoracao = addslashes($decoracao);
			$desenho_moda = addslashes($desenho_moda);
			$desenho_industrial = addslashes($desenho_industrial);
			$economia = addslashes($economia);
			$educacao_fisica = addslashes($educacao_fisica);
			$engenharia_aeroespacial = addslashes($engenharia_aeroespacial);
			$engenharia_biomedica = addslashes($engenharia_biomedica);
			$engenharia_civil = addslashes($engenharia_civil);
			$engenharia_armamentos = addslashes($engenharia_armamentos);
			$engenharia_minas = addslashes($engenharia_minas);
			$engenharia_transportes = addslashes($engenharia_transportes);
			$engenharia_mecatronica = addslashes($engenharia_mecatronica);
			$engenharia_nuclear = addslashes($engenharia_nuclear);
			$engenharia_textil = addslashes($engenharia_textil);
			$farmacia = addslashes($farmacia);
			$fisiologia = addslashes($fisiologia);
			$fonoaudiologia = addslashes($fonoaudiologia);
			$historia_natural = addslashes($historia_natural);
			$linguistica = addslashes($linguistica);
			$medicina_veterinaria = addslashes($medicina_veterinaria);
			$morfologia = addslashes($morfologia);
			$nutricao = addslashes($nutricao);
			$odontologia = addslashes($odontologia);
			$planejamento_urbano_regional = addslashes($planejamento_urbano_regional);
			$quimica_industrial = addslashes($quimica_industrial);
			$relacoes_internacionais = addslashes($relacoes_internacionais);
			$secretariado_executiva = addslashes($secretariado_executiva);
			$teologia = addslashes($teologia);
			$zootecnia = addslashes($zootecnia);
			$qagronomia = addslashes($qagronomia);
			$qarquitetura_urbanismo = addslashes($qarquitetura_urbanismo);
			$qbiologia_geral = addslashes($qbiologia_geral);
			$qdireito = addslashes($qdireito);
			$qeducacao = addslashes($qeducacao);
			$qfilosofia = addslashes($qfilosofia);
			$qgeociencias = addslashes($qgeociencias);
			$qhistoria = addslashes($qhistoria);
			$qmatematica = addslashes($qmatematica);
			$qquimica = addslashes($qquimica);
			$qsaude_coletiva = addslashes($qsaude_coletiva);
			$qturismo = addslashes($qturismo);
			$qantropologia = addslashes($qantropologia);
			$qarte = addslashes($qarte);
			$qcomunicacao_jornalismo = addslashes($qcomunicacao_jornalismo);
			$qecologia = addslashes($qecologia);
			$qengenharia_sanitaria = addslashes($qengenharia_sanitaria);
			$qfisica = addslashes($qfisica);
			$qgeografia = addslashes($qgeografia);
			$qletras = addslashes($qletras);
			$qpsicologia = addslashes($qpsicologia);
			$qrec_florestais_eng_florestal = addslashes($qrec_florestais_eng_florestal);
			$qsociologia = addslashes($qsociologia);
			$qadministracao = addslashes($qadministracao);
			$qadministracao_rural = addslashes($qadministracao_rural);
			$qastronomia = addslashes($qastronomia);
			$qbiomedicina = addslashes($qbiomedicina);
			$qbotanica = addslashes($qbotanica);
			$qcarreira_religiosa = addslashes($qcarreira_religiosa);
			$qciencia_informacao = addslashes($qciencia_informacao);
			$qciencia_politica = addslashes($qciencia_politica);
			$qciencias_atuariais = addslashes($qciencias_atuariais);
			$qcomunicacao = addslashes($qcomunicacao);
			$qdemografia = addslashes($qdemografia);
			$qdesenho_projetos = addslashes($qdesenho_projetos);
			$qdiplomacia = addslashes($qdiplomacia);
			$qeconomia_domestica = addslashes($qeconomia_domestica);
			$qenfermagem = addslashes($qenfermagem);
			$qengenharia_agricola = addslashes($qengenharia_agricola);
			$qengenharia_cartografica = addslashes($qengenharia_cartografica);
			$qengenharia_agrimensura = addslashes($qengenharia_agrimensura);
			$qengenharia_materiais_metalurgica = addslashes($qengenharia_materiais_metalurgica);
			$qengenharia_producao = addslashes($qengenharia_producao);
			$qengenharia_eletrica = addslashes($qengenharia_eletrica);
			$qengenharia_naval_oceanica = addslashes($qengenharia_naval_oceanica);
			$qengenharia_quimica = addslashes($qengenharia_quimica);
			$qestudos_sociais = addslashes($qestudos_sociais);
			$qfarmacologia = addslashes($qfarmacologia);
			$qfisioterapia_terapia_ocupacional = addslashes($qfisioterapia_terapia_ocupacional);
			$qgenetica = addslashes($qgenetica);
			$qimunologia = addslashes($qimunologia);
			$qmedicina = addslashes($qmedicina);
			$qmicrobiologia = addslashes($qmicrobiologia);
			$qmuseologia = addslashes($qmuseologia);
			$qoceanografia = addslashes($qoceanografia);
			$qparasitologia = addslashes($qparasitologia);
			$qprobabilidade_estatistica = addslashes($qprobabilidade_estatistica);
			$qrecursos_pesqueiros_engenharia_pesca = addslashes($qrecursos_pesqueiros_engenharia_pesca);
			$qrelacoes_publicas = addslashes($qrelacoes_publicas);
			$qservico_social = addslashes($qservico_social);
			$qzoologia = addslashes($qzoologia);
			$qadministracao_hospitalar = addslashes($qadministracao_hospitalar);
			$qarqueologia = addslashes($qarqueologia);
			$qbiofisica = addslashes($qbiofisica);
			$qbioquimica = addslashes($qbioquimica);
			$qcarreira_militar = addslashes($qcarreira_militar);
			$qciencia_computacao = addslashes($qciencia_computacao);
			$qciencia_tecnologia_alimentos = addslashes($qciencia_tecnologia_alimentos);
			$qciencias = addslashes($qciencias);
			$qciencias_sociais = addslashes($qciencias_sociais);
			$qdecoracao = addslashes($qdecoracao);
			$qdesenho_moda = addslashes($qdesenho_moda);
			$qdesenho_industrial = addslashes($qdesenho_industrial);
			$qeconomia = addslashes($qeconomia);
			$qeducacao_fisica = addslashes($qeducacao_fisica);
			$qengenharia_aeroespacial = addslashes($qengenharia_aeroespacial);
			$qengenharia_biomedica = addslashes($qengenharia_biomedica);
			$qengenharia_civil = addslashes($qengenharia_civil);
			$qengenharia_armamentos = addslashes($qengenharia_armamentos);
			$qengenharia_minas = addslashes($qengenharia_minas);
			$qengenharia_transportes = addslashes($qengenharia_transportes);
			$qengenharia_mecatronica = addslashes($qengenharia_mecatronica);
			$qengenharia_nuclear = addslashes($qengenharia_nuclear);
			$qengenharia_textil = addslashes($qengenharia_textil);
			$qfarmacia = addslashes($qfarmacia);
			$qfisiologia = addslashes($qfisiologia);
			$qfonoaudiologia = addslashes($qfonoaudiologia);
			$qhistoria_natural = addslashes($qhistoria_natural);
			$qlinguistica = addslashes($qlinguistica);
			$qmedicina_veterinaria = addslashes($qmedicina_veterinaria);
			$qmorfologia = addslashes($qmorfologia);
			$qnutricao = addslashes($qnutricao);
			$qodontologia = addslashes($qodontologia);
			$qplanejamento_urbano_regional = addslashes($qplanejamento_urbano_regional);
			$qquimica_industrial = addslashes($qquimica_industrial);
			$qrelacoes_internacionais = addslashes($qrelacoes_internacionais);
			$qsecretariado_executiva = addslashes($qsecretariado_executiva);
			$qteologia = addslashes($qteologia);
			$qzootecnia = addslashes($qzootecnia);
			$qarea_conhecimento = addslashes($qarea_conhecimento);
			
		    $sql = "UPDATE area_conhecimento SET agronomia='$agronomia',arquitetura_urbanismo='$arquitetura_urbanismo',biologia_geral='$biologia_geral',direito='$direito',educacao='$educacao',filosofia='$filosofia',geociencias='$geociencias',historia='$historia',matematica='$matematica',quimica='$quimica',saude_coletiva='$saude_coletiva',turismo='$turismo',antropologia='$antropologia',arte='$arte',comunicacao_jornalismo='$comunicacao_jornalismo',ecologia='$ecologia',engenharia_sanitaria='$engenharia_sanitaria',fisica='$fisica',geografia='$geografia',letras='$letras',psicologia='$psicologia',rec_florestais_eng_florestal='$rec_florestais_eng_florestal',sociologia='$sociologia',administracao='$administracao',administracao_rural='$administracao_rural',astronomia='$astronomia',biomedicina='$biomedicina',botanica='$botanica',carreira_religiosa='$carreira_religiosa',ciencia_informacao='$ciencia_informacao',ciencia_politica='$ciencia_politica',ciencias_atuariais='$ciencias_atuariais',comunicacao='$comunicacao',demografia='$demografia',desenho_projetos='$desenho_projetos',diplomacia='$diplomacia',economia_domestica='$economia_domestica',enfermagem='$enfermagem',engenharia_agricola='$engenharia_agricola',engenharia_cartografica='$engenharia_cartografica',engenharia_agrimensura='$engenharia_agrimensura',engenharia_materiais_metalurgica='$engenharia_materiais_metalurgica',engenharia_producao='$engenharia_producao',engenharia_eletrica='$engenharia_eletrica',engenharia_naval_oceanica='$engenharia_naval_oceanica',engenharia_quimica='$engenharia_quimica',estudos_sociais='$estudos_sociais',farmacologia='$farmacologia',fisioterapia_terapia_ocupacional='$fisioterapia_terapia_ocupacional',genetica='$genetica',imunologia='$imunologia',medicina='$medicina',microbiologia='$microbiologia',museologia='$museologia',oceanografia='$oceanografia',parasitologia='$parasitologia',probabilidade_estatistica='$probabilidade_estatistica',recursos_pesqueiros_engenharia_pesca='$recursos_pesqueiros_engenharia_pesca',relacoes_publicas='$relacoes_publicas',servico_social='$servico_social',zoologia='$zoologia',administracao_hospitalar='$administracao_hospitalar',arqueologia='$arqueologia',biofisica='$biofisica',bioquimica='$bioquimica',carreira_militar='$carreira_militar',ciencia_computacao='$ciencia_computacao',ciencia_tecnologia_alimentos='$ciencia_tecnologia_alimentos',ciencias='$ciencias',ciencias_sociais='$ciencias_sociais',decoracao='$decoracao',desenho_moda='$desenho_moda',desenho_industrial='$desenho_industrial',economia='$economia',educacao_fisica='$educacao_fisica',engenharia_aeroespacial='$engenharia_aeroespacial',engenharia_biomedica='$engenharia_biomedica',engenharia_civil='$engenharia_civil',engenharia_armamentos='$engenharia_armamentos',engenharia_minas='$engenharia_minas',engenharia_transportes='$engenharia_transportes',engenharia_mecatronica='$engenharia_mecatronica',engenharia_nuclear='$engenharia_nuclear',engenharia_textil='$engenharia_textil',farmacia='$farmacia',fisiologia='$fisiologia',fonoaudiologia='$fonoaudiologia',historia_natural='$historia_natural',linguistica='$linguistica',medicina_veterinaria='$medicina_veterinaria',morfologia='$morfologia',nutricao='$nutricao',odontologia='$odontologia',planejamento_urbano_regional='$planejamento_urbano_regional',quimica_industrial='$quimica_industrial',relacoes_internacionais='$relacoes_internacionais',secretariado_executiva='$secretariado_executiva',teologia='$teologia',zootecnia='$zootecnia',qagronomia='$qagronomia',qarquitetura_urbanismo='$qarquitetura_urbanismo',qbiologia_geral='$qbiologia_geral',qdireito='$qdireito',qeducacao='$qeducacao',qfilosofia='$qfilosofia',qgeociencias='$qgeociencias',qhistoria='$qhistoria',qmatematica='$qmatematica',qquimica='$qquimica',qsaude_coletiva='$qsaude_coletiva',qturismo='$qturismo',qantropologia='$qantropologia',qarte='$qarte',qcomunicacao_jornalismo='$qcomunicacao_jornalismo',qecologia='$qecologia',qengenharia_sanitaria='$qengenharia_sanitaria',qfisica='$qfisica',qgeografia='$qgeografia',qletras='$qletras',qpsicologia='$qpsicologia',qrec_florestais_eng_florestal='$qrec_florestais_eng_florestal',qsociologia='$qsociologia',qadministracao='$qadministracao',qadministracao_rural='$qadministracao_rural',qastronomia='$qastronomia',qbiomedicina='$qbiomedicina',qbotanica='$qbotanica',qcarreira_religiosa='$qcarreira_religiosa',qciencia_informacao='$qciencia_informacao',qciencia_politica='$qciencia_politica',qciencias_atuariais='$qciencias_atuariais',qcomunicacao='$qcomunicacao',qdemografia='$qdemografia',qdesenho_projetos='$qdesenho_projetos',qdiplomacia='$qdiplomacia',qeconomia_domestica='$qeconomia_domestica',qenfermagem='$qenfermagem',qengenharia_agricola='$qengenharia_agricola',qengenharia_cartografica='$qengenharia_cartografica',qengenharia_agrimensura='$qengenharia_agrimensura',qengenharia_materiais_metalurgica='$qengenharia_materiais_metalurgica',qengenharia_producao='$qengenharia_producao',qengenharia_eletrica='$qengenharia_eletrica',qengenharia_naval_oceanica='$qengenharia_naval_oceanica',qengenharia_quimica='$qengenharia_quimica',qestudos_sociais='$qestudos_sociais',qfarmacologia='$qfarmacologia',qfisioterapia_terapia_ocupacional='$qfisioterapia_terapia_ocupacional',qgenetica='$qgenetica',qimunologia='$qimunologia',qmedicina='$qmedicina',qmicrobiologia='$qmicrobiologia',qmuseologia='$qmuseologia',qoceanografia='$qoceanografia',qparasitologia='$qparasitologia',qprobabilidade_estatistica='$qprobabilidade_estatistica',qrecursos_pesqueiros_engenharia_pesca='$qrecursos_pesqueiros_engenharia_pesca',qrelacoes_publicas='$qrelacoes_publicas',qservico_social='$qservico_social',qzoologia='$qzoologia',qadministracao_hospitalar='$qadministracao_hospitalar',qarqueologia='$qarqueologia',qbiofisica='$qbiofisica',qbioquimica='$qbioquimica',qcarreira_militar='$qcarreira_militar',qciencia_computacao='$qciencia_computacao',qciencia_tecnologia_alimentos='$qciencia_tecnologia_alimentos',qciencias='$qciencias',qciencias_sociais='$qciencias_sociais',qdecoracao='$qdecoracao',qdesenho_moda='$qdesenho_moda',qdesenho_industrial='$qdesenho_industrial',qeconomia='$qeconomia',qeducacao_fisica='$qeducacao_fisica',qengenharia_aeroespacial='$qengenharia_aeroespacial',qengenharia_biomedica='$qengenharia_biomedica',qengenharia_civil='$qengenharia_civil',qengenharia_armamentos='$qengenharia_armamentos',qengenharia_minas='$qengenharia_minas',qengenharia_transportes='$qengenharia_transportes',qengenharia_mecatronica='$qengenharia_mecatronica',qengenharia_nuclear='$qengenharia_nuclear',qengenharia_textil='$qengenharia_textil',qfarmacia='$qfarmacia',qfisiologia='$qfisiologia',qfonoaudiologia='$qfonoaudiologia',qhistoria_natural='$qhistoria_natural',qlinguistica='$qlinguistica',qmedicina_veterinaria='$qmedicina_veterinaria',qmorfologia='$qmorfologia',qnutricao='$qnutricao',qodontologia='$qodontologia',qplanejamento_urbano_regional='$qplanejamento_urbano_regional',qquimica_industrial='$qquimica_industrial',qrelacoes_internacionais='$qrelacoes_internacionais',qsecretariado_executiva='$qsecretariado_executiva',qteologia='$qteologia',qzootecnia='$qzootecnia',qarea_conhecimento='$qarea_conhecimento' WHERE id = $id";
	
			$result = DBFactory::query($sql);
			
			DBFactory::closeConnection();
			
			return $result;
		}
		
		public function deleteData($obj){
			DBFactory::getConnection();
			$id = $obj->getId();
			
			$sql = "DELETE FROM area_conhecimento WHERE id='$id'";
			$result = DBFactory::query($sql);
			
			DBFactory::closeConnection();
			return $result;
		}
		
		public function selectData($word){
			DBFactory::getConnection();
			
			$word = addslashes($word);
			
			$sql = "SELECT * FROM area_conhecimento WHERE agronomia LIKE '$word%'";
			$result = DBFactory::query($sql);
			
			$i=0;
			
			while($data = mysql_fetch_array($result,MYSQL_ASSOC)){
				$obj[$i] = new Area_conhecimento($data['id'],$data['agronomia'],$data['arquitetura_urbanismo'],$data['biologia_geral'],$data['direito'],$data['educacao'],$data['filosofia'],$data['geociencias'],$data['historia'],$data['matematica'],$data['quimica'],$data['saude_coletiva'],$data['turismo'],$data['antropologia'],$data['arte'],$data['comunicacao_jornalismo'],$data['ecologia'],$data['engenharia_sanitaria'],$data['fisica'],$data['geografia'],$data['letras'],$data['psicologia'],$data['rec_florestais_eng_florestal'],$data['sociologia'],$data['administracao'],$data['administracao_rural'],$data['astronomia'],$data['biomedicina'],$data['botanica'],$data['carreira_religiosa'],$data['ciencia_informacao'],$data['ciencia_politica'],$data['ciencias_atuariais'],$data['comunicacao'],$data['demografia'],$data['desenho_projetos'],$data['diplomacia'],$data['economia_domestica'],$data['enfermagem'],$data['engenharia_agricola'],$data['engenharia_cartografica'],$data['engenharia_agrimensura'],$data['engenharia_materiais_metalurgica'],$data['engenharia_producao'],$data['engenharia_eletrica'],$data['engenharia_naval_oceanica'],$data['engenharia_quimica'],$data['estudos_sociais'],$data['farmacologia'],$data['fisioterapia_terapia_ocupacional'],$data['genetica'],$data['imunologia'],$data['medicina'],$data['microbiologia'],$data['museologia'],$data['oceanografia'],$data['parasitologia'],$data['probabilidade_estatistica'],$data['recursos_pesqueiros_engenharia_pesca'],$data['relacoes_publicas'],$data['servico_social'],$data['zoologia'],$data['administracao_hospitalar'],$data['arqueologia'],$data['biofisica'],$data['bioquimica'],$data['carreira_militar'],$data['ciencia_computacao'],$data['ciencia_tecnologia_alimentos'],$data['ciencias'],$data['ciencias_sociais'],$data['decoracao'],$data['desenho_moda'],$data['desenho_industrial'],$data['economia'],$data['educacao_fisica'],$data['engenharia_aeroespacial'],$data['engenharia_biomedica'],$data['engenharia_civil'],$data['engenharia_armamentos'],$data['engenharia_minas'],$data['engenharia_transportes'],$data['engenharia_mecatronica'],$data['engenharia_nuclear'],$data['engenharia_textil'],$data['farmacia'],$data['fisiologia'],$data['fonoaudiologia'],$data['historia_natural'],$data['linguistica'],$data['medicina_veterinaria'],$data['morfologia'],$data['nutricao'],$data['odontologia'],$data['planejamento_urbano_regional'],$data['quimica_industrial'],$data['relacoes_internacionais'],$data['secretariado_executiva'],$data['teologia'],$data['zootecnia'],$data['qagronomia'],$data['qarquitetura_urbanismo'],$data['qbiologia_geral'],$data['qdireito'],$data['qeducacao'],$data['qfilosofia'],$data['qgeociencias'],$data['qhistoria'],$data['qmatematica'],$data['qquimica'],$data['qsaude_coletiva'],$data['qturismo'],$data['qantropologia'],$data['qarte'],$data['qcomunicacao_jornalismo'],$data['qecologia'],$data['qengenharia_sanitaria'],$data['qfisica'],$data['qgeografia'],$data['qletras'],$data['qpsicologia'],$data['qrec_florestais_eng_florestal'],$data['qsociologia'],$data['qadministracao'],$data['qadministracao_rural'],$data['qastronomia'],$data['qbiomedicina'],$data['qbotanica'],$data['qcarreira_religiosa'],$data['qciencia_informacao'],$data['qciencia_politica'],$data['qciencias_atuariais'],$data['qcomunicacao'],$data['qdemografia'],$data['qdesenho_projetos'],$data['qdiplomacia'],$data['qeconomia_domestica'],$data['qenfermagem'],$data['qengenharia_agricola'],$data['qengenharia_cartografica'],$data['qengenharia_agrimensura'],$data['qengenharia_materiais_metalurgica'],$data['qengenharia_producao'],$data['qengenharia_eletrica'],$data['qengenharia_naval_oceanica'],$data['qengenharia_quimica'],$data['qestudos_sociais'],$data['qfarmacologia'],$data['qfisioterapia_terapia_ocupacional'],$data['qgenetica'],$data['qimunologia'],$data['qmedicina'],$data['qmicrobiologia'],$data['qmuseologia'],$data['qoceanografia'],$data['qparasitologia'],$data['qprobabilidade_estatistica'],$data['qrecursos_pesqueiros_engenharia_pesca'],$data['qrelacoes_publicas'],$data['qservico_social'],$data['qzoologia'],$data['qadministracao_hospitalar'],$data['qarqueologia'],$data['qbiofisica'],$data['qbioquimica'],$data['qcarreira_militar'],$data['qciencia_computacao'],$data['qciencia_tecnologia_alimentos'],$data['qciencias'],$data['qciencias_sociais'],$data['qdecoracao'],$data['qdesenho_moda'],$data['qdesenho_industrial'],$data['qeconomia'],$data['qeducacao_fisica'],$data['qengenharia_aeroespacial'],$data['qengenharia_biomedica'],$data['qengenharia_civil'],$data['qengenharia_armamentos'],$data['qengenharia_minas'],$data['qengenharia_transportes'],$data['qengenharia_mecatronica'],$data['qengenharia_nuclear'],$data['qengenharia_textil'],$data['qfarmacia'],$data['qfisiologia'],$data['qfonoaudiologia'],$data['qhistoria_natural'],$data['qlinguistica'],$data['qmedicina_veterinaria'],$data['qmorfologia'],$data['qnutricao'],$data['qodontologia'],$data['qplanejamento_urbano_regional'],$data['qquimica_industrial'],$data['qrelacoes_internacionais'],$data['qsecretariado_executiva'],$data['qteologia'],$data['qzootecnia'],$data['qarea_conhecimento']);	
				$i++;
			}
			
			DBFactory::closeConnection();
			
			return $obj;
		}
		
		public function selectDataForCode($id){
			
			DBFactory::getConnection();
			echo DBFactory::msg(DBFactory::getConnection());
			
			$id = (int) $id;
			$id = mysql_real_escape_string($id);
			$sql = "SELECT * FROM area_conhecimento WHERE id=$id";

			$result = mysql_query($sql);
			
			$i = 0;
			$data = mysql_fetch_array($result);
			$obj = new Area_conhecimento($data['id'],$data['agronomia'],$data['arquitetura_urbanismo'],$data['biologia_geral'],$data['direito'],$data['educacao'],$data['filosofia'],$data['geociencias'],$data['historia'],$data['matematica'],$data['quimica'],$data['saude_coletiva'],$data['turismo'],$data['antropologia'],$data['arte'],$data['comunicacao_jornalismo'],$data['ecologia'],$data['engenharia_sanitaria'],$data['fisica'],$data['geografia'],$data['letras'],$data['psicologia'],$data['rec_florestais_eng_florestal'],$data['sociologia'],$data['administracao'],$data['administracao_rural'],$data['astronomia'],$data['biomedicina'],$data['botanica'],$data['carreira_religiosa'],$data['ciencia_informacao'],$data['ciencia_politica'],$data['ciencias_atuariais'],$data['comunicacao'],$data['demografia'],$data['desenho_projetos'],$data['diplomacia'],$data['economia_domestica'],$data['enfermagem'],$data['engenharia_agricola'],$data['engenharia_cartografica'],$data['engenharia_agrimensura'],$data['engenharia_materiais_metalurgica'],$data['engenharia_producao'],$data['engenharia_eletrica'],$data['engenharia_naval_oceanica'],$data['engenharia_quimica'],$data['estudos_sociais'],$data['farmacologia'],$data['fisioterapia_terapia_ocupacional'],$data['genetica'],$data['imunologia'],$data['medicina'],$data['microbiologia'],$data['museologia'],$data['oceanografia'],$data['parasitologia'],$data['probabilidade_estatistica'],$data['recursos_pesqueiros_engenharia_pesca'],$data['relacoes_publicas'],$data['servico_social'],$data['zoologia'],$data['administracao_hospitalar'],$data['arqueologia'],$data['biofisica'],$data['bioquimica'],$data['carreira_militar'],$data['ciencia_computacao'],$data['ciencia_tecnologia_alimentos'],$data['ciencias'],$data['ciencias_sociais'],$data['decoracao'],$data['desenho_moda'],$data['desenho_industrial'],$data['economia'],$data['educacao_fisica'],$data['engenharia_aeroespacial'],$data['engenharia_biomedica'],$data['engenharia_civil'],$data['engenharia_armamentos'],$data['engenharia_minas'],$data['engenharia_transportes'],$data['engenharia_mecatronica'],$data['engenharia_nuclear'],$data['engenharia_textil'],$data['farmacia'],$data['fisiologia'],$data['fonoaudiologia'],$data['historia_natural'],$data['linguistica'],$data['medicina_veterinaria'],$data['morfologia'],$data['nutricao'],$data['odontologia'],$data['planejamento_urbano_regional'],$data['quimica_industrial'],$data['relacoes_internacionais'],$data['secretariado_executiva'],$data['teologia'],$data['zootecnia'],$data['qagronomia'],$data['qarquitetura_urbanismo'],$data['qbiologia_geral'],$data['qdireito'],$data['qeducacao'],$data['qfilosofia'],$data['qgeociencias'],$data['qhistoria'],$data['qmatematica'],$data['qquimica'],$data['qsaude_coletiva'],$data['qturismo'],$data['qantropologia'],$data['qarte'],$data['qcomunicacao_jornalismo'],$data['qecologia'],$data['qengenharia_sanitaria'],$data['qfisica'],$data['qgeografia'],$data['qletras'],$data['qpsicologia'],$data['qrec_florestais_eng_florestal'],$data['qsociologia'],$data['qadministracao'],$data['qadministracao_rural'],$data['qastronomia'],$data['qbiomedicina'],$data['qbotanica'],$data['qcarreira_religiosa'],$data['qciencia_informacao'],$data['qciencia_politica'],$data['qciencias_atuariais'],$data['qcomunicacao'],$data['qdemografia'],$data['qdesenho_projetos'],$data['qdiplomacia'],$data['qeconomia_domestica'],$data['qenfermagem'],$data['qengenharia_agricola'],$data['qengenharia_cartografica'],$data['qengenharia_agrimensura'],$data['qengenharia_materiais_metalurgica'],$data['qengenharia_producao'],$data['qengenharia_eletrica'],$data['qengenharia_naval_oceanica'],$data['qengenharia_quimica'],$data['qestudos_sociais'],$data['qfarmacologia'],$data['qfisioterapia_terapia_ocupacional'],$data['qgenetica'],$data['qimunologia'],$data['qmedicina'],$data['qmicrobiologia'],$data['qmuseologia'],$data['qoceanografia'],$data['qparasitologia'],$data['qprobabilidade_estatistica'],$data['qrecursos_pesqueiros_engenharia_pesca'],$data['qrelacoes_publicas'],$data['qservico_social'],$data['qzoologia'],$data['qadministracao_hospitalar'],$data['qarqueologia'],$data['qbiofisica'],$data['qbioquimica'],$data['qcarreira_militar'],$data['qciencia_computacao'],$data['qciencia_tecnologia_alimentos'],$data['qciencias'],$data['qciencias_sociais'],$data['qdecoracao'],$data['qdesenho_moda'],$data['qdesenho_industrial'],$data['qeconomia'],$data['qeducacao_fisica'],$data['qengenharia_aeroespacial'],$data['qengenharia_biomedica'],$data['qengenharia_civil'],$data['qengenharia_armamentos'],$data['qengenharia_minas'],$data['qengenharia_transportes'],$data['qengenharia_mecatronica'],$data['qengenharia_nuclear'],$data['qengenharia_textil'],$data['qfarmacia'],$data['qfisiologia'],$data['qfonoaudiologia'],$data['qhistoria_natural'],$data['qlinguistica'],$data['qmedicina_veterinaria'],$data['qmorfologia'],$data['qnutricao'],$data['qodontologia'],$data['qplanejamento_urbano_regional'],$data['qquimica_industrial'],$data['qrelacoes_internacionais'],$data['qsecretariado_executiva'],$data['qteologia'],$data['qzootecnia'],$data['qarea_conhecimento']);
	
			DBFactory::closeConnection();
			
			return $obj;
		}
		
		public function allData(){
			$sql = "SELECT * FROM area_conhecimento ORDER BY id DESC";

			DBFactory::getConnection();
			echo DBFactory::msg(DBFactory::getConnection());
			$result = mysql_query($sql);
			
			$i = 0;
			while($data = mysql_fetch_array($result)){
				$obj[$i] = new Area_conhecimento($data['id'],$data['agronomia'],$data['arquitetura_urbanismo'],$data['biologia_geral'],$data['direito'],$data['educacao'],$data['filosofia'],$data['geociencias'],$data['historia'],$data['matematica'],$data['quimica'],$data['saude_coletiva'],$data['turismo'],$data['antropologia'],$data['arte'],$data['comunicacao_jornalismo'],$data['ecologia'],$data['engenharia_sanitaria'],$data['fisica'],$data['geografia'],$data['letras'],$data['psicologia'],$data['rec_florestais_eng_florestal'],$data['sociologia'],$data['administracao'],$data['administracao_rural'],$data['astronomia'],$data['biomedicina'],$data['botanica'],$data['carreira_religiosa'],$data['ciencia_informacao'],$data['ciencia_politica'],$data['ciencias_atuariais'],$data['comunicacao'],$data['demografia'],$data['desenho_projetos'],$data['diplomacia'],$data['economia_domestica'],$data['enfermagem'],$data['engenharia_agricola'],$data['engenharia_cartografica'],$data['engenharia_agrimensura'],$data['engenharia_materiais_metalurgica'],$data['engenharia_producao'],$data['engenharia_eletrica'],$data['engenharia_naval_oceanica'],$data['engenharia_quimica'],$data['estudos_sociais'],$data['farmacologia'],$data['fisioterapia_terapia_ocupacional'],$data['genetica'],$data['imunologia'],$data['medicina'],$data['microbiologia'],$data['museologia'],$data['oceanografia'],$data['parasitologia'],$data['probabilidade_estatistica'],$data['recursos_pesqueiros_engenharia_pesca'],$data['relacoes_publicas'],$data['servico_social'],$data['zoologia'],$data['administracao_hospitalar'],$data['arqueologia'],$data['biofisica'],$data['bioquimica'],$data['carreira_militar'],$data['ciencia_computacao'],$data['ciencia_tecnologia_alimentos'],$data['ciencias'],$data['ciencias_sociais'],$data['decoracao'],$data['desenho_moda'],$data['desenho_industrial'],$data['economia'],$data['educacao_fisica'],$data['engenharia_aeroespacial'],$data['engenharia_biomedica'],$data['engenharia_civil'],$data['engenharia_armamentos'],$data['engenharia_minas'],$data['engenharia_transportes'],$data['engenharia_mecatronica'],$data['engenharia_nuclear'],$data['engenharia_textil'],$data['farmacia'],$data['fisiologia'],$data['fonoaudiologia'],$data['historia_natural'],$data['linguistica'],$data['medicina_veterinaria'],$data['morfologia'],$data['nutricao'],$data['odontologia'],$data['planejamento_urbano_regional'],$data['quimica_industrial'],$data['relacoes_internacionais'],$data['secretariado_executiva'],$data['teologia'],$data['zootecnia'],$data['qagronomia'],$data['qarquitetura_urbanismo'],$data['qbiologia_geral'],$data['qdireito'],$data['qeducacao'],$data['qfilosofia'],$data['qgeociencias'],$data['qhistoria'],$data['qmatematica'],$data['qquimica'],$data['qsaude_coletiva'],$data['qturismo'],$data['qantropologia'],$data['qarte'],$data['qcomunicacao_jornalismo'],$data['qecologia'],$data['qengenharia_sanitaria'],$data['qfisica'],$data['qgeografia'],$data['qletras'],$data['qpsicologia'],$data['qrec_florestais_eng_florestal'],$data['qsociologia'],$data['qadministracao'],$data['qadministracao_rural'],$data['qastronomia'],$data['qbiomedicina'],$data['qbotanica'],$data['qcarreira_religiosa'],$data['qciencia_informacao'],$data['qciencia_politica'],$data['qciencias_atuariais'],$data['qcomunicacao'],$data['qdemografia'],$data['qdesenho_projetos'],$data['qdiplomacia'],$data['qeconomia_domestica'],$data['qenfermagem'],$data['qengenharia_agricola'],$data['qengenharia_cartografica'],$data['qengenharia_agrimensura'],$data['qengenharia_materiais_metalurgica'],$data['qengenharia_producao'],$data['qengenharia_eletrica'],$data['qengenharia_naval_oceanica'],$data['qengenharia_quimica'],$data['qestudos_sociais'],$data['qfarmacologia'],$data['qfisioterapia_terapia_ocupacional'],$data['qgenetica'],$data['qimunologia'],$data['qmedicina'],$data['qmicrobiologia'],$data['qmuseologia'],$data['qoceanografia'],$data['qparasitologia'],$data['qprobabilidade_estatistica'],$data['qrecursos_pesqueiros_engenharia_pesca'],$data['qrelacoes_publicas'],$data['qservico_social'],$data['qzoologia'],$data['qadministracao_hospitalar'],$data['qarqueologia'],$data['qbiofisica'],$data['qbioquimica'],$data['qcarreira_militar'],$data['qciencia_computacao'],$data['qciencia_tecnologia_alimentos'],$data['qciencias'],$data['qciencias_sociais'],$data['qdecoracao'],$data['qdesenho_moda'],$data['qdesenho_industrial'],$data['qeconomia'],$data['qeducacao_fisica'],$data['qengenharia_aeroespacial'],$data['qengenharia_biomedica'],$data['qengenharia_civil'],$data['qengenharia_armamentos'],$data['qengenharia_minas'],$data['qengenharia_transportes'],$data['qengenharia_mecatronica'],$data['qengenharia_nuclear'],$data['qengenharia_textil'],$data['qfarmacia'],$data['qfisiologia'],$data['qfonoaudiologia'],$data['qhistoria_natural'],$data['qlinguistica'],$data['qmedicina_veterinaria'],$data['qmorfologia'],$data['qnutricao'],$data['qodontologia'],$data['qplanejamento_urbano_regional'],$data['qquimica_industrial'],$data['qrelacoes_internacionais'],$data['qsecretariado_executiva'],$data['qteologia'],$data['qzootecnia'],$data['qarea_conhecimento']);	
				$i++;
			}
			
			DBFactory::closeConnection();
			
			return $obj;
		}	
	    
		public function dbMsg(){
			return DBFactory::msg();
		}
		
		public static function getLastInsertedId(){
			return self::$lastId;		
		}

		private static function setLastId(){
			$aux = DBFactory::getLastId();
			if ($aux != -1){
				self::$lastId = $aux;
			}else{
				echo "Erro ao alterar LastID";
			}
		}
		
	}
?>